/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 29
#define YY_END_OF_BUFFER 30
static yyconst short int yy_accept[499] =
    {   0,
        1,    1,   30,   29,    1,   29,   28,   25,   26,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,    1,    0,    2,   28,    0,
        0,   19,   18,    0,    0,    0,    0,    0,    0,    0,
       17,    0,    0,    0,    0,    0,   16,    8,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    2,    0,    0,
        8,    0,    0,    0,    0,    8,   20,    0,    0,    0,
        0,    0,    0,    3,    3,    3,   20,    0,    0,    0,
        0,    0,    0,    0,    0,   20,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   20,    0,    8,

        8,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   14,    0,   22,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   23,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   21,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   15,   15,   15,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        7,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        9,    0,    0,    0,    4,    0,    0,   27,    0,    0,

        0,    0,   24,    0,    0,    0,    0,    0,    0,    4,
        4,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    5,    0,    0,    0,    0,    0,    5,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   12,    0,    0,
       10,    0,    0,    0,    0,    0,    0,    0,    0,   13,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    6,    0,   11,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    4,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    6,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    8,    9,    1,
        1,    1,    1,   10,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       12,    1,   13,    1,   14,    1,   15,   16,   17,   18,

       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   38,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[40] =
    {   0,
        1,    2,    3,    3,    1,    1,    4,    1,    1,    1,
        4,    1,    1,    1,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4
    } ;

static yyconst short int yy_base[515] =
    {   0,
        0,    0,  905,  906,   37,  898,  896,  906,  906,  879,
       14,   27,  872,   18,   27,  880,   24,  880,   26,  866,
      877,   28,   44,   51,  874,   64,  875,    0,  887,  865,
      874,  906,  906,  852,  865,  861,   46,  857,  853,  857,
      906,  865,  863,  863,  851,  847,  906,   67,  859,  859,
      846,  843,   69,   47,   53,  853,  855,    0,  857,  844,
      906,  838,  851,  851,  841,   72,  849,  833,  840,  843,
       77,  836,  837,   75,   77,   82,  843,   69,  835,   87,
      834,  838,  835,  837,  837,  836,   91,  835,  820,  833,
      817,   93,  831,   82,  834,  829,  812,  827,  817,   98,

      100,  824,  827,  822,  808,  821,  819,  809,  809,  802,
      806,  818,  103,  815,  797,  805,  105,  796,  906,  795,
      812,  807,  792,  790,  790,  791,  799,  795,  794,  800,
      799,  798,  796,  795,  906,  780,  793,  796,  107,  788,
      792,  790,  789,  117,  787,  790,  789,  784,  787,  776,
       87,  773,  906,  780,  766,  764,  121,  123,  781,  125,
      777,  780,  780,  772,  758,  757,  770,  127,  775,  784,
      129,  751,  131,  763,  105,  765,  133,  768,  131,  136,
      747,  768,  745,  752,  141,  147,  157,  763,  129,  152,
      167,    0,    0,  169,  178,  180,  190,  764,  168,  162,

      769,  769,  195,  746,  740,  737,  199,  741,  158,  752,
      171,  203,  197,  208,  218,  227,  762,  213,  226,  733,
      740,  749,  752,  734,  190,  745,  194,  732,  192,  237,
      731,  211,  243,  248,  257,  274,  279,  729,  232,  734,
      906,  745,  735,  734,  242,  725,  721,  284,  723,  719,
      318,  352,    0,    0,  721,  238,  732,  250,  736,  295,
      289,  741,  725,  721,  727,  255,  716,  715,  298,  300,
      312,  329,  338,  357,  371,  401,  275,  260,  257,  294,
      340,  720,  711,  283,  331,  710,  316,  256,  388,  349,
      719,  720,  718,  383,  403,  413,  732,  731,  360,  393,

      334,  352,  296,  415,  397,  304,  712,  713,  398,  418,
      428,  433,  439,  452,  697,  710,  711,  696,  445,  707,
      706,  696,  343,  707,  379,  355,  444,  704,  404,  449,
      479,  465,  710,  689,  688,  701,  689,  443,  700,  451,
      484,  687,  683,  488,  685,  681,  127,  692,  679,  689,
      472,  493,  434,  691,  690,  693,  677,  673,  502,  675,
      671,  683,  667,  475,  668,  681,  679,  485,  511,  513,
      522,  527,  683,  682,  532,  536,  663,  682,  223,  675,
      678,  671,  478,  538,  525,  683,  547,  655,  658,  552,
      906,  450,  505,  673,    0,  654,  534,  906,  656,  460,

      667,  518,  906,  653,  669,  660,  557,  559,  568,  668,
      906,  661,  411,  649,  645,  570,  647,  643,  653,  643,
      653,  641,  656,  648,  663,  648,  654,  645,  643,  906,
      573,  643,  560,  630,  642,  654,  627,  631,  631,  624,
      628,  636,  633,  578,  634,  618,  618,  619,  627,  633,
      614,  611,  630,  629,  581,  621,  625,  906,  622,  627,
      906,  614,  603,  610,  621,  521,  617,  621,  613,  906,
      583,  588,  594,  558,  451,  599,  604,  609,  617,  608,
      599,  585,  599,  587,  597,  594,  592,  588,  570,  578,
      547,  514,  507,  490,  906,  487,  906,  906,  620,  494,

      480,  396,  622,  354,  320,  624,  293,  626,  192,  163,
      118,   95,   73,   48
    } ;

static yyconst short int yy_def[515] =
    {   0,
      498,    1,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  499,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  500,  498,  498,  498,  499,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  500,  500,  500,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,

      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  501,  498,  498,  498,  502,  503,
      498,  498,  498,  498,  501,  501,  501,  498,  498,  498,
      502,  191,  191,  503,  503,  503,  503,  498,  504,  498,

      498,  498,  498,  498,  498,  498,  498,  191,  191,  191,
      191,  503,  505,  504,  504,  504,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  191,  191,  506,
      191,  191,  503,  503,  505,  505,  505,  498,  498,  498,
      498,  498,  498,  498,  507,  498,  498,  508,  498,  498,
      508,  506,  252,  252,  252,  252,  252,  252,  252,  252,
      503,  498,  498,  498,  498,  509,  498,  498,  507,  507,
      507,  508,  508,  508,  508,  508,  276,  276,  276,  276,
      207,  252,  252,  252,  252,  252,  252,  510,  503,  498,
      498,  498,  498,  509,  509,  509,  498,  498,  498,  498,

      276,  276,  276,  276,  276,  276,  498,  252,  251,  252,
      510,  510,  510,  503,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  276,  276,  498,  252,  498,
      510,  503,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  276,  498,  252,  498,
      331,  503,  511,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  276,  498,  252,  498,  331,  503,  511,
      511,  511,  498,  498,  498,  498,  498,  498,  276,  498,
      252,  498,  331,  503,  498,  498,  498,  498,  498,  498,
      498,  512,  276,  498,  252,  498,  331,  498,  498,  498,

      498,  498,  498,  498,  498,  498,  512,  512,  512,  276,
      498,  498,  331,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  331,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  513,  498,  498,  498,  498,
      513,  513,  513,  514,  498,  514,  514,  514,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,    0,  498,  498,

      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498
    } ;

static yyconst short int yy_nxt[946] =
    {   0,
        4,    4,    5,    5,    4,    6,    7,    8,    9,   10,
        4,    4,    4,    4,   11,   12,   13,    4,   14,    4,
       15,    4,   16,   17,    4,   18,    4,   19,   20,   21,
        4,   22,   23,    4,    4,   24,   25,    4,    4,   26,
       26,   31,   33,   37,   45,   39,   32,   33,   38,   34,
       49,  478,   43,   74,   46,   40,   50,   75,   35,   27,
       41,   51,   52,   53,   54,   55,   26,   26,   63,   69,
       69,   73,   73,   77,   87,   87,  473,   41,   64,   92,
       92,   74,   94,   74,   78,   75,   27,   75,   74,   87,
       87,   95,   75,   87,   87,   92,   92,   88,  409,  108,

      116,  116,  117,  117,  109,  129,  129,  117,  117,  151,
      151,  185,   88,  162,  110,  186,   88,  111,  106,  155,
      155,  372,  163,  168,  168,  170,  170,  172,  172,  168,
      168,  181,  181,  183,  183,  189,  189,  191,  194,  194,
      498,  192,  195,  201,  201,  204,  196,  185,  364,  201,
      201,  186,  202,  185,  206,  206,  169,  186,  202,  201,
      201,  205,  169,  185,  217,  217,  313,  186,  202,  207,
      207,  194,  212,  191,  214,  195,  229,  192,  215,  196,
      194,  212,  194,  212,  195,  208,  195,  209,  196,  232,
      196,  230,  194,  212,  210,  296,  195,  220,  220,  211,

      196,  207,  207,  235,  230,  233,  234,  236,  247,  195,
      238,  238,  250,  196,  214,  240,  240,  224,  215,  225,
      238,  238,  228,  248,  214,  230,  226,  248,  215,  238,
      238,  227,  219,  214,  264,  264,  498,  215,  241,  251,
      251,  228,  393,  252,  230,  194,  212,  253,  269,  195,
      233,  234,  270,  196,  195,  255,  284,  256,  196,  262,
      262,  294,  311,  235,  257,  295,  312,  236,  287,  258,
      498,  285,  259,  498,  261,  305,  262,  262,  303,  261,
      235,  262,  262,  285,  236,  235,  272,  272,  498,  236,
      273,  194,  212,  304,  274,  195,  271,  251,  251,  196,

      299,  299,  299,  299,  269,  302,  269,  498,  270,  498,
      270,  289,  306,  283,  299,  299,  285,  498,  269,  276,
      251,  251,  270,  237,  273,  285,  254,  304,  274,  304,
      259,  272,  272,  309,  309,  273,  277,  304,  278,  274,
      300,  300,  281,  281,  273,  279,  283,  498,  274,  285,
      280,  315,  315,  276,  281,  281,  326,  216,  252,  300,
      300,  343,  253,  273,  276,  498,  259,  274,  498,  301,
      255,  307,  256,  300,  300,  347,  344,  273,  322,  257,
      323,  274,  304,  282,  258,  319,  319,  324,  301,  294,
      194,  212,  325,  295,  195,  300,  300,  346,  196,  193,

      309,  309,  301,  300,  300,  319,  319,  273,  314,  294,
      498,  274,  344,  295,  288,  319,  319,  327,  327,  294,
      309,  309,  284,  295,  307,  349,  424,  304,  498,  301,
      330,  330,  301,  313,  311,  330,  330,  285,  312,  311,
      370,  330,  330,  312,  371,  311,  327,  327,  285,  312,
      276,  330,  330,  259,  194,  212,  407,  498,  195,  331,
      408,  358,  196,  337,  331,  338,  479,  194,  212,  361,
      331,  195,  339,  332,  480,  196,  359,  340,  415,  276,
      350,  330,  330,  187,  359,  311,  362,  362,  498,  312,
      363,  363,  368,  416,  313,  194,  212,   76,  352,  195,

      313,  351,  497,  196,  376,  376,  383,  313,  379,  496,
      331,  397,  369,  194,  212,  385,  385,  195,  498,  370,
      410,  196,  495,  371,  385,  385,  384,  471,  370,  385,
      385,  472,  371,  370,  388,  388,  418,  371,  389,  389,
      194,  212,  390,  399,  195,  400,  398,  494,  196,  404,
      404,  416,  401,  413,  389,  389,  313,  402,  390,  422,
      422,  422,  422,  407,  476,  407,  493,  408,  477,  408,
      422,  422,  425,  425,  407,  436,  436,  438,  408,  431,
      452,  452,  439,  463,  463,  475,  475,  484,  484,  471,
      475,  475,  440,  472,  471,  441,  475,  475,  472,  492,

      471,  481,  481,  491,  472,  476,  481,  481,  490,  477,
      476,  481,  481,  489,  477,  476,  488,  487,  486,  477,
       58,  485,   58,   58,  197,  197,  254,  254,  275,  275,
      483,  482,  482,  455,  474,  455,  470,  469,  468,  467,
      466,  465,  455,  464,  462,  461,  460,  459,  458,  457,
      456,  455,  454,  453,  451,  450,  449,  448,  447,  446,
      445,  444,  443,  442,  437,  435,  434,  433,  432,  431,
      313,  430,  429,  428,  427,  426,  416,  416,  416,  416,
      423,  498,  421,  420,  419,  417,  414,  412,  411,  406,
      405,  403,  396,  395,  394,  392,  391,  387,  386,  382,

      381,  380,  378,  377,  359,  359,  359,  359,  375,  374,
      373,  367,  366,  365,  344,  344,  344,  344,  360,  357,
      356,  355,  354,  353,  348,  345,  342,  341,  341,  336,
      335,  334,  333,  329,  328,  321,  320,  318,  317,  316,
      310,  285,  308,  298,  297,  293,  292,  291,  290,  288,
      286,  283,  248,  248,  248,  248,  268,  267,  266,  265,
      263,  260,  230,  249,  246,  245,  244,  243,  242,  239,
      231,  228,  223,  222,  221,  219,  218,  213,  203,  200,
      163,  199,  198,  190,  188,  184,  182,  180,  179,  178,
      177,  176,  173,  175,  174,  173,  171,  167,  166,  165,

      164,  161,  160,  159,  158,  157,  156,  154,  153,  139,
      152,  150,  149,  148,  147,  146,  145,   61,  144,  143,
      142,  141,  140,  139,  138,  137,  136,  135,  134,  133,
      132,  131,  130,  128,  127,  126,  125,  124,  123,  122,
      121,  120,  119,  118,  115,   32,  114,  113,  112,  107,
      105,  104,  103,  102,   32,  101,  100,   99,   98,   97,
       96,   32,   93,   61,   91,   90,   89,   32,   86,   85,
       84,   83,   82,   81,   80,   79,   41,   72,   71,   70,
       47,   41,   68,   67,   66,   65,   41,   41,   62,   61,
       60,   47,   59,   29,   57,   56,   48,   47,   44,   42,

       36,   30,   29,   28,  498,    3,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498
    } ;

static yyconst short int yy_chk[946] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    5,
        5,   11,   12,   14,   19,   15,   11,   17,   14,   12,
       22,  514,   17,   54,   19,   15,   22,   54,   12,    5,
       15,   22,   23,   23,   24,   24,   26,   26,   37,   48,
       48,   53,   53,   55,   66,   66,  513,   23,   37,   71,
       71,   74,   78,   75,   55,   74,   26,   75,   76,   80,
       80,   78,   76,   87,   87,   92,   92,   66,  512,   94,

      100,  100,  101,  101,   94,  113,  113,  117,  117,  139,
      139,  175,   80,  151,   94,  175,   87,   94,   92,  144,
      144,  511,  151,  157,  157,  158,  158,  160,  160,  168,
      168,  171,  171,  173,  173,  177,  177,  179,  180,  180,
      347,  179,  180,  185,  185,  189,  180,  185,  347,  186,
      186,  185,  185,  186,  190,  190,  157,  186,  186,  187,
      187,  189,  168,  187,  200,  200,  510,  187,  187,  191,
      191,  194,  194,  191,  199,  194,  209,  191,  199,  194,
      195,  195,  196,  196,  195,  191,  196,  191,  195,  211,
      196,  209,  197,  197,  191,  509,  197,  203,  203,  191,

      197,  207,  207,  213,  211,  212,  212,  213,  225,  212,
      214,  214,  227,  212,  214,  218,  218,  207,  214,  207,
      215,  215,  229,  225,  215,  229,  207,  227,  215,  216,
      216,  207,  219,  216,  239,  239,  379,  216,  219,  230,
      230,  232,  379,  230,  232,  233,  233,  230,  245,  233,
      234,  234,  245,  233,  234,  230,  256,  230,  234,  235,
      235,  266,  288,  235,  230,  266,  288,  235,  258,  230,
      279,  256,  230,  278,  233,  279,  236,  236,  278,  234,
      236,  237,  237,  258,  236,  237,  248,  248,  277,  237,
      248,  261,  261,  278,  248,  261,  507,  260,  260,  261,

      269,  269,  270,  270,  269,  277,  270,  280,  269,  303,
      270,  261,  280,  284,  271,  271,  284,  306,  271,  248,
      251,  251,  271,  505,  251,  260,  260,  280,  251,  303,
      260,  272,  272,  285,  285,  272,  251,  306,  251,  272,
      273,  273,  281,  281,  273,  251,  287,  301,  273,  287,
      251,  290,  290,  251,  252,  252,  301,  504,  252,  274,
      274,  323,  252,  274,  272,  302,  285,  274,  326,  273,
      252,  281,  252,  275,  275,  326,  323,  275,  299,  252,
      299,  275,  302,  252,  252,  294,  294,  299,  274,  294,
      289,  289,  299,  294,  289,  300,  300,  325,  289,  502,

      309,  309,  275,  276,  276,  295,  295,  276,  289,  295,
      305,  276,  325,  295,  276,  296,  296,  304,  304,  296,
      310,  310,  329,  296,  300,  329,  413,  305,  304,  309,
      311,  311,  276,  413,  311,  312,  312,  329,  311,  312,
      353,  313,  313,  312,  353,  313,  327,  327,  310,  313,
      304,  330,  330,  310,  314,  314,  392,  327,  314,  311,
      392,  338,  314,  319,  312,  319,  475,  332,  332,  340,
      313,  332,  319,  314,  475,  332,  338,  319,  400,  327,
      330,  331,  331,  501,  340,  331,  341,  341,  364,  331,
      344,  344,  351,  400,  351,  352,  352,  500,  332,  352,

      383,  331,  496,  352,  359,  359,  368,  368,  364,  494,
      331,  383,  352,  369,  369,  370,  370,  369,  393,  370,
      393,  369,  493,  370,  371,  371,  369,  466,  371,  372,
      372,  466,  371,  372,  375,  375,  402,  372,  376,  376,
      384,  384,  376,  385,  384,  385,  384,  492,  384,  387,
      387,  402,  385,  397,  390,  390,  397,  385,  390,  407,
      407,  408,  408,  407,  474,  408,  491,  407,  474,  408,
      409,  409,  416,  416,  409,  431,  431,  433,  409,  431,
      444,  444,  433,  455,  455,  471,  471,  482,  482,  471,
      472,  472,  433,  471,  472,  433,  473,  473,  472,  490,

      473,  476,  476,  489,  473,  476,  477,  477,  488,  476,
      477,  478,  478,  487,  477,  478,  486,  485,  484,  478,
      499,  483,  499,  499,  503,  503,  506,  506,  508,  508,
      481,  480,  479,  469,  468,  467,  465,  464,  463,  462,
      460,  459,  457,  456,  454,  453,  452,  451,  450,  449,
      448,  447,  446,  445,  443,  442,  441,  440,  439,  438,
      437,  436,  435,  434,  432,  429,  428,  427,  426,  425,
      424,  423,  422,  421,  420,  419,  418,  417,  415,  414,
      412,  410,  406,  405,  404,  401,  399,  396,  394,  389,
      388,  386,  382,  381,  380,  378,  377,  374,  373,  367,

      366,  365,  363,  362,  361,  360,  358,  357,  356,  355,
      354,  350,  349,  348,  346,  345,  343,  342,  339,  337,
      336,  335,  334,  333,  328,  324,  322,  321,  320,  318,
      317,  316,  315,  308,  307,  298,  297,  293,  292,  291,
      286,  283,  282,  268,  267,  265,  264,  263,  262,  259,
      257,  255,  250,  249,  247,  246,  244,  243,  242,  240,
      238,  231,  228,  226,  224,  223,  222,  221,  220,  217,
      210,  208,  206,  205,  204,  202,  201,  198,  188,  184,
      183,  182,  181,  178,  176,  174,  172,  170,  169,  167,
      166,  165,  164,  163,  162,  161,  159,  156,  155,  154,

      152,  150,  149,  148,  147,  146,  145,  143,  142,  141,
      140,  138,  137,  136,  134,  133,  132,  131,  130,  129,
      128,  127,  126,  125,  124,  123,  122,  121,  120,  118,
      116,  115,  114,  112,  111,  110,  109,  108,  107,  106,
      105,  104,  103,  102,   99,   98,   97,   96,   95,   93,
       91,   90,   89,   88,   86,   85,   84,   83,   82,   81,
       79,   77,   73,   72,   70,   69,   68,   67,   65,   64,
       63,   62,   60,   59,   57,   56,   52,   51,   50,   49,
       46,   45,   44,   43,   42,   40,   39,   38,   36,   35,
       34,   31,   30,   29,   27,   25,   21,   20,   18,   16,

       13,   10,    7,    6,    3,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#define INITIAL 0
#line 74 "scanner.l"
	int key_count = 0;
	int var_count =0;
	int text_count=0;
#line 742 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 79 "scanner.l"

#line 895 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 499 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 906 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 80 "scanner.l"
{} 
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 81 "scanner.l"
{ printf("This is a Comment\n");}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 83 "scanner.l"
{printf("This is a variabl\n");}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 85 "scanner.l"
{
													printf("If statement\n");
													key_count++;
													}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 92 "scanner.l"
{
													printf("If statement\n");
													key_count++;
													}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 99 "scanner.l"
{
																	printf("User Defined Function\n");
                                                                  }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 103 "scanner.l"
{printf("Array\n");}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 105 "scanner.l"
{
														 printf("Keyword\n");
														 key_count++;
														}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 110 "scanner.l"
{printf("Header Declaration!\n");}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 112 "scanner.l"
{printf("This is main Function\n");}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 115 "scanner.l"
{ 
													 printf("For Loop\n");
													 key_count++;
													}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 120 "scanner.l"
{
													 printf("While Loop\n");
													 key_count++;
													}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 125 "scanner.l"
{
													printf("Else-if statement\n");
													key_count++;
													}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 129 "scanner.l"
{
	printf("Else statement\n");
	key_count++;
	}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 134 "scanner.l"
{ printf("This is a variable\n"); var_count++; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 136 "scanner.l"
{printf("Logical Operator\n");}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 138 "scanner.l"
{printf("Relational Operator\n");}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 140 "scanner.l"
{printf("Increment/Decrement Operator\n");}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 142 "scanner.l"
{printf("Assignment Operator\n");}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 144 "scanner.l"
{printf("Arithmetic Operator\n");}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 146 "scanner.l"
{printf("Data Type\n");}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 148 "scanner.l"
{printf("Block Start\n");}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 150 "scanner.l"
{printf("Block End\n");}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 152 "scanner.l"
{
				  printf("Read Function\n");
                }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 156 "scanner.l"
{printf("Colon(punctuation)\n");}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 157 "scanner.l"
{printf("SemiColon(punctuation)\n");}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 159 "scanner.l"
{
										printf("This is text for print\n");
										text_count++; 
									}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 165 "scanner.l"
{printf("It's a Number\n");}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 167 "scanner.l"
ECHO;
	YY_BREAK
#line 1151 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 499 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 499 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 498);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 167 "scanner.l"


int yywrap(){
	return 1;
}

main()
{
	freopen("flex project.txt","r",stdin);
	printf("Starting\n");
	yylex();
	printf("Total Keyword: %d and variable = %d and text = %d ",key_count,var_count,text_count);
}